### PR TITLE
Code-style changes and Zebra compatibility

### PR DESCRIPTION
**Pull request by NSExceptional**
Zebra renamed the view controller Batchomatic expects to put the button on (not sure why they renamed it, I will try to get it re-named back…)

Anyway, this PR also does a lot of general code style cleanup:
- Ignores some theos-related folders (`.gitignore`)
- Use `BOOL` instead of `bool`, and `YES`/`NO` instead of `true`/`false`
- Add comment block headers to every source file
- Use the latest SDK in the Makefile
- Removes redundant method declarations in interfaces
- Removes redundant `== true/false` statements
- Makes Batchomatic properties `nonatomic` (you should always do this unless you want `atomic` properties for some reason)
- Curbs excessively long lines to around ~120 characters

Everything still compiles fine. Besides the bugfix and changes to the Makefile, all source changes are purely semantic and couldn't possibly introduce any bugs.

I see that there is another PR about Zebra. I'm not sure what the hold up is there, but if you want I'll wait until that gets merged, then rebase my changes on top of that.

### CODE REVIEW

**Comment by captinc** [comment]
nonatomic is not thread-safe, so if there is any chance of thread issues, you should use atomic (the default). dispatch_async is definitely used in Batchomatic, but I can’t remember off the top of my head if I access properties in a non-thread-safe manner

Zebra’s search view controller was renamed on purpose - it will not be changed back. wstyres already informed me of this & Batchomatic will reflect this change

I appreciate this PR, thanks! I’ll look into this one (as well as the other one) when I make the next update

**Comment by NSExceptional** [comment]
There's zero chance of threading issues with regards to what Batchomatic does from what I can tell, I did take a look around

A little history: as turns out, you almost never need to use atomic properties at all in real life scenarios; the `atomic` behavior being default is largely regarded as a mistake. For example: if you have an NSMutableArray property, adding things to it is not atomic even if the property is atomic. It's a pretty useless feature in almost all cases; especially in app development. :P

As for Zebra: well, I'm sure it was on purpose, but I think having longer class names when both names are equally descriptive is not a good thing, lol. I work on zebra too so I might change this back unless he really wants it to have `Table` in the name for whatever reason 😅

**Comment by captinc** [comment]
Ah ok. Thanks for explaining!

**Comment by NSExceptional** [comment]
@captinc Can you merge this please and update the tweak?

**Comment by captinc** [comment]
Pull requests are not being accepted at this time.

**Comment by NSExceptional** [comment]
Can I ask why?

**Comment by captinc** [comment]
When time allows, the tweak will be rewritten from scratch with newfound knowledge.

**Pull request closed without merging**
