### PR TITLE
fix

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by proprdev** [comment]
fuck you

**Comment by captinc** [comment]
whoops, didn't mean to delete that lol, i honestly didn't know repo owners can moderate the comments section until now

**Comment by ghost** [comment]
asshat

**Comment by captinc** [comment]
lmao, i actually found this funny though, well played 👏. in the spirit of entertainment, i'd like to [return the favor](https://cdn.discordapp.com/emojis/817189359165374513.png?v=1)

**Comment by proprdev** [comment]
[heres another](https://cdn.discordapp.com/emojis/816542591860473896.png?v=1)

**Pull request closed without merging**
