### PR TITLE
Fully support Zebra 1.1

### PR DESCRIPTION
**Pull request by eve0415**
This PR will fix to support Zebra 1.1.x

- "Repos" has been changed to "Sources"
- Zebra now uses import table when adding entire sources via sources.list
- darkModeEnabled is now deprecated as it will now use system dark mode as default.
- remove checkrain’s repo as it is not used or updated to the latest anymore. (Use bingner’s instead)

Known bug

- ~~Removing sources via Batchomatic will make Zebra instantly crash. This is because I couldn't find out how to get (short) URL from ZBSource.~~ Fixed as of fadd45c
- ~~When Zebra is in light mode manually, Batchomatic isn't readable as everything is white. This is because I haven't replace `darkModeEnabled` to `InterfaceStyleKey`.~~
We do not have to think about this as Zebra does not have its own dark mode anymore.
Fixed as of 6d5befc
- cannot import sources  because there is no txt file name `reposToAdd.txt` in `tmp` folder (Edit: It looks like it is deleting `tmp/batchomatic` folder before actually importing sources. Tested on Cydia also)

Note

I have updated for myself to backup my jailbroken state as I got a new iPhone.
I haven't had any problem `creating online.deb`, `queuing tweaks`, and `removing all tweaks`, `removing all sources`.
Tested on iOS 13.5, Zebra 1.1.9

### CODE REVIEW

**Comment by captinc** [comment]
Thanks! I’ll review everything when I make the new update

**Comment by eve0415** [comment]
Update: Fix crash when trying to remove sources via Batchomatic.

**Comment by TheNoim** [comment]
Tried your branch with iOS 13.4.1 (backup) and 13.5 (restore) and it worked fine.

**Comment by eve0415** [comment]
@TheNoim Did you get the repository back via Batchomatic or did you manually added?

**Comment by TheNoim** [comment]
Which repo do you mean?

**Comment by eve0415** [comment]
I mean all repos

**Comment by TheNoim** [comment]
> @TheNoim Did you get the repository back via Batchomatic or did you manually added?

Non of both. They were already present after installing zebra via cydia. 

My steps:

1. Install cydia via checkr1n app
2. Install zebra via cydia
3. Install filza via zebra
4. Install batchomatic and batchomatic offline deb via filza
5. Restore via batchomatic

**Comment by eve0415** [comment]
Ok, thank you

**Comment by TheNoim** [comment]
@captinc When will you update the tweak or merge this?

**Comment by captinc** [comment]
As soon as I have time to work on it. Currently, I am still in school & also working on a different project

**Comment by captinc** [comment]
Pull requests are not being accepted at this time.

**Pull request closed without merging**
